### ISSUE TITLE
OCTGN Crash after table setup

### ISSUE THREAD

**Issue by sruman** [blakewedwards/l5r-lcg-octgn#3]
Steps to reproduce:

Host new game ( name: test, password: test )
Set to two-sided table and no spectators
Start game with only 1 player
Load attached deck
Setup table (via either right-click or ctrl-shift-s)
Wait 5-10 seconds (may be connected to moving mouse across table but not sure, it's not immediate) and octgn crashes

Console Log (not much here):

wiley is ready
Unlocking game
wiley loads a deck.
wiley sets up.
The Kami choose wiley as the first player.

Log files and deck attached.
[log.txt](https://github.com/blakewedwards/l5r-lcg-octgn/files/1242177/log.txt)

[crash_deck.txt](https://github.com/blakewedwards/l5r-lcg-octgn/files/1242195/crash_deck.txt)

**Comment by sruman** [comment]
As an update I tried another deck (attached) and a similar thing happened although seemed to take a bit longer (10 seconds after some mousing over things).  Error is similar, here's the trace:

FATAL 2017-08-22 10:32:49,035 3.1.297.0 [1] Octgn.OctgnApp [(null)] - UNHANDLED EXCEPTION [Game Legend of the Five Rings LCG 0.0.1.0 bb0f02e7-2a6f-4ae3-84a2-c501b4176844] [Username wiley] 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Octgn.Library.Exceptions.UserMessageException: There is an invalid proxy definition. Please contact the game developer and let them know.
   at Octgn.ProxyGenerator.ProxyGenerator.GenerateProxy(BlockManager manager, String rootPath, TemplateDefinition template, Dictionary`2 values, String specialPath) in C:\projects\octgn\octgnFX\Octgn.ProxyGenerator\ProxyGenerator.cs:line 29
   at Octgn.ProxyGenerator.ProxyDefinition.GenerateProxyImage(Dictionary`2 values) in C:\projects\octgn\octgnFX\Octgn.ProxyGenerator\ProxyDefinition.cs:line 30
   at Octgn.ProxyGenerator.ProxyDefinition.SaveProxyImage(Dictionary`2 values, String path) in C:\projects\octgn\octgnFX\Octgn.ProxyGenerator\ProxyDefinition.cs:line 37
   at Octgn.Core.DataExtensionMethods.CardExtensionMethods.GetProxyPicture(ICard card) in C:\projects\octgn\octgnFX\Octgn.Core\DataExtensionMethods\CardExtensionMethods.cs:line 105
   at Octgn.Play.Card.IsProxy() in C:\projects\octgn\octgnFX\Octgn\Play\Card.cs:line 500
   at Octgn.Play.PlayWindow.CardHovered(Object sender, CardEventArgs e) in C:\projects\octgn\octgnFX\Octgn\Play\PlayWindow.xaml.cs:line 697
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.RoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at Octgn.Play.Gui.CardControl.OnPropertyChanged(DependencyPropertyChangedEventArgs e) in C:\projects\octgn\octgnFX\Octgn\Play\Gui\CardControl.xaml.cs:line 995
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, IList`1 otherOrigins, DeferredElementTreeState& oldTreeState, Action`2 originChangedAction)
   at System.Windows.Input.MouseDevice.ChangeMouseOver(IInputElement mouseOver, Int32 timestamp)
   at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Octgn.OctgnApp.Main()

**Comment by blakewedwards** [comment]
Did you delete any of the contents of the OCTGN/ImageDatabase/bb0f02e7-2a6f-4ae3-84a2-c501b4176844 folder? That's the only way I've been able to generate an invalid proxy definition error on setup so far. If so, you can uninstall and reinstall the plugin and the issue will be resolved. I'll update the proxy definition as well to handle this more gracefully, but hopefully that workaround helps you in the interim.

**Comment by sruman** [comment]
Uninstalled and then re-downloaded and re-installed the plug-in with the same outcome unfortunately.  Would you happen to have a checksum value for a fully working .....8444 sub-directory I could check?  I never delted anything from it but worth checking.

**Comment by sruman** [comment]
Tried again with new version of OCTGN (299) and the plugin (0.0.1.1) with the same result unfortunately (stack trace below, seems the same).  I uninstalled plug-in before and deleted old LocalImages directory before installing new plug-in.  Perhaps you could attach a deck you find is working and I could try that?

ATAL 2017-08-28 20:55:03,809 3.1.299.0 [1] Octgn.OctgnApp [(null)] - UNHANDLED EXCEPTION [Game Legend of the Five Rings LCG 0.0.1.1 bb0f02e7-2a6f-4ae3-84a2-c501b4176844] [Username wiley] 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Octgn.Library.Exceptions.UserMessageException: There is an invalid proxy definition. Please contact the game developer and let them know.
   at Octgn.ProxyGenerator.ProxyGenerator.GenerateProxy(BlockManager manager, String rootPath, TemplateDefinition template, Dictionary`2 values, String specialPath) in C:\projects\octgn\octgnFX\Octgn.ProxyGenerator\ProxyGenerator.cs:line 29
   at Octgn.ProxyGenerator.ProxyDefinition.GenerateProxyImage(Dictionary`2 values) in C:\projects\octgn\octgnFX\Octgn.ProxyGenerator\ProxyDefinition.cs:line 30
   at Octgn.ProxyGenerator.ProxyDefinition.SaveProxyImage(Dictionary`2 values, String path) in C:\projects\octgn\octgnFX\Octgn.ProxyGenerator\ProxyDefinition.cs:line 37
   at Octgn.Core.DataExtensionMethods.CardExtensionMethods.GetProxyPicture(ICard card) in C:\projects\octgn\octgnFX\Octgn.Core\DataExtensionMethods\CardExtensionMethods.cs:line 105
   at Octgn.Play.Card.IsProxy() in C:\projects\octgn\octgnFX\Octgn\Play\Card.cs:line 500
   at Octgn.Play.PlayWindow.CardHovered(Object sender, CardEventArgs e) in C:\projects\octgn\octgnFX\Octgn\Play\PlayWindow.xaml.cs:line 697
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.RoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at Octgn.Play.Gui.CardControl.OnPropertyChanged(DependencyPropertyChangedEventArgs e) in C:\projects\octgn\octgnFX\Octgn\Play\Gui\CardControl.xaml.cs:line 995
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, IList`1 otherOrigins, DeferredElementTreeState& oldTreeState, Action`2 originChangedAction)
   at System.Windows.Input.MouseDevice.ChangeMouseOver(IInputElement mouseOver, Int32 timestamp)
   at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Octgn.OctgnApp.Main()

**Comment by blakewedwards** [comment]
I've created an alternate version of 0.0.1.1 that has a blank default for proxies. You'll need to uninstall and remove the other L5R packages from LocalFeed, then install this version. The card that's failing should now show up as a blank card with its name in the center, hopefully this helps narrow down the problem

https://drive.google.com/open?id=0By_ODAjR2bBEb3Uzc3NwSjRZWHM

**Comment by blakewedwards** [comment]
Ordering is important to forget the old version I think. First uninstall and close octgn, then clear LocalFeed and add the new one.

**Comment by sruman** [comment]
Thanks.  Tried it out and no longer crashing (with and without the latest image pack for the cards).  I looked through the log but couldn't find a message indicate what might have been missing but I'm not sure what I'm looking for exactly.  
[nocrash_log.txt](https://github.com/blakewedwards/l5r-lcg-octgn/files/1265497/nocrash_log.txt)

**Comment by blakewedwards** [comment]
It wouldn't have caused anything to appear in the log, but whatever card it was having problems trying to generate a proxy of should now appear as a blank (solid white) card with its name in the center. Should be in any of hand/decks or on the table. Can look at all cards in a deck by right clicking it and looking at all cards. If an image pack is installed you might not be able to see the proxy.

**Comment by sruman** [comment]
I uninstalled (deleted the image directory) the image pack, uninstalled the build you gave above and then re-installed to try and find it.  Still seems to be stable and I looked through all the dynasty and conflict cards in the deck that was previously crashing without finding any that was completely blank except the name.  All had the appropriate symbols, strengths, etc.

**Comment by sruman** [comment]
The latest version, 0.1.2, seems to have fixed the issues. Thanks.

**Comment by blakewedwards** [comment]
Great, glad it's sorted.
